name: bayes_course

channels:
  - conda-forge
dependencies:
  - python=3.7
  - conda-forge::arviz
  - cython
  - cpuonly
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - conda-forge::jupyterlab
  - lxml
  - matplotlib
  - mkl-service
  - notebook
  - numpy
  - pandas
  - patsy
  - pip
  - pymc3
  - pydot
  - python-graphviz
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - theano
  - xlrd
