name: bayes_course

channels:
  - conda-forge
  - gpytorch
  - pytorch
dependencies:
  - python=3.6
  - cython
  - cpuonly
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - conda-forge::jupyterlab
  - gpytorch::gpytorch
  - lxml
  - matplotlib
  - mkl-service
  - notebook
  - numpy
  - pandas
  - patsy
  - pip
  - pymc3
  - pydot
  - python-graphviz
  - pytorch::pytorch
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - theano
  - torchvision
  - xlrd
  - pip:
      - arviz
      - tensorflow==2.0.0
      - tfp-nightly

